-- MySQL Script generated by MySQL Workbench
-- Tue Feb 27 16:16:41 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema SER322db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SER322db` ;

-- -----------------------------------------------------
-- Schema SER322db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SER322db` DEFAULT CHARACTER SET latin1 ;
USE `SER322db` ;

-- -----------------------------------------------------
-- Table `SER322db`.`Distribution_Center`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SER322db`.`Distribution_Center` ;

CREATE TABLE IF NOT EXISTS `SER322db`.`Distribution_Center` (
  `dcID` INT(11) NOT NULL AUTO_INCREMENT,
  `dcName` VARCHAR(128) NOT NULL,
  `dcStreet` VARCHAR(128) NOT NULL,
  `dcCity` VARCHAR(128) NOT NULL,
  `dcState` VARCHAR(128) NOT NULL,
  `dcZip` INT(13) NOT NULL,
  PRIMARY KEY (`dcID`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `SER322db`.`Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SER322db`.`Products` ;

CREATE TABLE IF NOT EXISTS `SER322db`.`Products` (
  `pID` INT(11) NOT NULL AUTO_INCREMENT,
  `pCost` DECIMAL(13,2) NULL DEFAULT NULL,
  `pName` VARCHAR(128) NOT NULL,
  `pDepartment` VARCHAR(128) NULL DEFAULT NULL,
  `pWeight` VARCHAR(128) NULL DEFAULT NULL,
  PRIMARY KEY (`pID`))
ENGINE = InnoDB
AUTO_INCREMENT = 42
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `SER322db`.`Holds`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SER322db`.`Holds` ;

CREATE TABLE IF NOT EXISTS `SER322db`.`Holds` (
  `Qty` INT(11) NULL DEFAULT NULL,
  `Distribution_Center_dcID` INT(11) NOT NULL,
  `Products_pID` INT(11) NOT NULL,
  PRIMARY KEY (`Distribution_Center_dcID`, `Products_pID`),
  CONSTRAINT `fk_Contains_Distribution_Center1`
    FOREIGN KEY (`Distribution_Center_dcID`)
    REFERENCES `SER322db`.`Distribution_Center` (`dcID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Holds_Products1`
    FOREIGN KEY (`Products_pID`)
    REFERENCES `SER322db`.`Products` (`pID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Contains_Distribution_Center1_idx` ON `SER322db`.`Holds` (`Distribution_Center_dcID` ASC);

CREATE INDEX `fk_Holds_Products1_idx` ON `SER322db`.`Holds` (`Products_pID` ASC);


-- -----------------------------------------------------
-- Table `SER322db`.`Retail_Locations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SER322db`.`Retail_Locations` ;

CREATE TABLE IF NOT EXISTS `SER322db`.`Retail_Locations` (
  `rID` INT(11) NOT NULL AUTO_INCREMENT,
  `rName` VARCHAR(128) NOT NULL,
  `rStreet` VARCHAR(128) NOT NULL,
  `rCity` VARCHAR(128) NOT NULL,
  `rState` VARCHAR(128) NOT NULL,
  `rZip` INT(13) NOT NULL,
  PRIMARY KEY (`rID`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `SER322db`.`Sells`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SER322db`.`Sells` ;

CREATE TABLE IF NOT EXISTS `SER322db`.`Sells` (
  `Sales_Price` DECIMAL(13,2) NULL DEFAULT NULL,
  `Date` DATETIME NULL DEFAULT NULL,
  `Qty` INT(11) NULL DEFAULT NULL,
  `Retail_Locations_rID` INT(11) NOT NULL DEFAULT '0',
  `Products_pID` INT(11) NOT NULL DEFAULT '0',
  `transactionID` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`transactionID`),
  CONSTRAINT `fk_Sells_Products1`
    FOREIGN KEY (`Products_pID`)
    REFERENCES `SER322db`.`Products` (`pID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sells_Retail_Locations1`
    FOREIGN KEY (`Retail_Locations_rID`)
    REFERENCES `SER322db`.`Retail_Locations` (`rID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Sells_Retail_Locations1_idx` ON `SER322db`.`Sells` (`Retail_Locations_rID` ASC);

CREATE INDEX `fk_Sells_Products1_idx` ON `SER322db`.`Sells` (`Products_pID` ASC);


-- -----------------------------------------------------
-- Table `SER322db`.`Supplies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SER322db`.`Supplies` ;

CREATE TABLE IF NOT EXISTS `SER322db`.`Supplies` (
  `Qty` INT(11) NULL DEFAULT NULL,
  `Date` DATETIME NULL DEFAULT NULL,
  `Cost` DECIMAL(13,2) NULL DEFAULT NULL,
  `Retail_Locations_rID` INT(11) NOT NULL,
  `Distribution_Center_dcID` INT(11) NOT NULL,
  `Products_pID` INT(11) NOT NULL,
  PRIMARY KEY (`Retail_Locations_rID`, `Distribution_Center_dcID`, `Products_pID`),
  CONSTRAINT `fk_Supplies_Distribution_Center1`
    FOREIGN KEY (`Distribution_Center_dcID`)
    REFERENCES `SER322db`.`Distribution_Center` (`dcID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Supplies_Products1`
    FOREIGN KEY (`Products_pID`)
    REFERENCES `SER322db`.`Products` (`pID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Supplies_Retail_Locations1`
    FOREIGN KEY (`Retail_Locations_rID`)
    REFERENCES `SER322db`.`Retail_Locations` (`rID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Supplies_Distribution_Center1_idx` ON `SER322db`.`Supplies` (`Distribution_Center_dcID` ASC);

CREATE INDEX `fk_Supplies_Products1_idx` ON `SER322db`.`Supplies` (`Products_pID` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
